{{- if .Values.imageCredentials.createSecret }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" .Values.imageCredentials }}
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.secretName }}
  labels:
{{ include "deploy.labels" . | indent 4 }}  
type: kubernetes.io/dockerconfigjson
{{- end }}

