{{- if .Values.confFiles  }}
{{- if .Values.confFiles.files  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.fullname" . }}-conffiles
  labels: 
{{ include "deploy.labels" . | indent 4 }}
type: Opaque
data:
{{- range .Values.confFiles.files }}
  {{ .name | quote }}: |
  {{- if .content -}}
    {{ tpl .content $ | b64enc | nindent 4 }}
  {{- else }}
    {{ tpl ($.Files.Get .file) $ | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
