{{ if .Values.secretproviderclass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretproviderclass.name }}
  labels:
{{ include "deploy.labels" . | indent 4 }}
  annotations:
{{ include "deploy.annotations" . | indent 4 }}   
spec:
  provider: {{ .Values.secretproviderclass.provider }}
  secretObjects:
   {{- toYaml .Values.secretproviderclass.secretObjects | nindent 4 }}
  parameters:
   {{- toYaml .Values.secretproviderclass.parameters | nindent 4 }}
{{ end }}