{{- if .Values.tlsSecrets }}
{{- range $name, $tls := .Values.tlsSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
{{ include "deploy.labels" $ | indent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- $tls.crt | nindent 4 }}
  tls.key: |
    {{- $tls.key | nindent 4 }}
{{- end }}
{{- end }}
