{{- if .Values.vault.enabled }}
{{- if .Values.vault.staticsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.fullname" . }}-sa
  annotations:
    kubernetes.io/service-account.name: {{ include "deploy.fullname" . }}-sa
  labels:
{{ include "deploy.labels" . | indent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}