{{- if .Values.vault.enabled }}
{{- if .Values.vault.staticsecret }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "deploy.fullname" . }}-static
  labels:
{{ include "deploy.labels" . | indent 4 }}
spec:
{{- include "VaultStaticSecret" . }}
{{- end }}
{{- end }}